version: 2.1

jobs:
  test:
    docker:
      - image: circleci/node:14
    steps:
      - checkout
      - run: npm install
      - run: npm test

workflows:
  version: 2
  test_and_merge:
    jobs:
      - test:
          filters:
            branches:
              only: /^(?!main$).*/  # run on all branches except main
      - approve_merge:
          requires:
            - test
          filters:
            branches:
              only: main