version: 2
jobs:
  test:
    name: Test job
    docker:
      - image: circleci/node:14
    steps:
      - checkout
      - restore_cache:
          keys:
            - dependencies-{{ checksum "package.json" }}
            - dependencies-
      - run: npm install
      - save_cache:
          paths:
            - node_modules
          key: dependencies-{{ checksum "package.json" }}
      - run: npm test

  approval:
    name: Approval job
    type: approval

workflows:
  version: 2
  unit_test:
    jobs:
      - test:
          filters:
            branches:
              only: main

  approve_changes:
    jobs:
      - approval:
          filters:
            branches:
              only: /.*/