version: 2
jobs:
  test:
    docker:
      - image: circleci/node:14
    steps:
      - checkout
      - run: npm install
      - run: npm test

workflows:
  version: 2
  main_branch:
    jobs:
      - test:
          filters:
            branches:
              only: main
      - approval:
          type: approval