version: 2.1

jobs:
  unit_test:
    docker:
      - image: circleci/node:14
    steps:
      - checkout
      - run: npm install
      - run: npm test

workflows:
  build-and-test:
    jobs:
      - unit_test
        filters:
          branches:
            only: main
